### ISSUE TITLE
lein immutant war with resource-paths set in project.clj directory issue

### ISSUE THREAD

**Issue by jwymanm** [immutant/lein-immutant#106]
Operating System: Windows 2008r2
Java: Server 1.8.0_25

Creating "overrides" inside a resource path listed under a war resource-paths parameter in project.clj has a dos style path kept intact once the war file is created.

Example project.clj entry:

:immutant { :war { :resource-paths ["war"] } }

Example war created (first 3 files showing issue were in resource-paths directory "war"):

\WEB-INF\lib/google-closure-library-0.0-20140718-946a7d39.jar
\WEB-INF/web.xml
\WEB-INF/jboss-deployment-structure.xml
 WEB-INF/lib/portal-standalone.jar
 WEB-INF/jboss-web.xml
 WEB-INF/lib/wunderboss-wildfly-1.x.incremental.174.jar
 WEB-INF/lib/wildfly-2.x.incremental.414.jar
 WEB-INF/lib/tools.nrepl-0.2.3.jar
 WEB-INF/jboss-deployment-structure.xml
 WEB-INF/web.xml
 META-INF/app.properties

**Comment by tobias** [comment]
We just released 2.0.0-beta1 with this fix (and this is the only change over alpha1).
