### ISSUE TITLE
Alternetive to specifing jboss home

### ISSUE THREAD

**Issue by chipset1** [immutant/lein-immutant#115]
Hi, 

I'm in a situation where Wildfly is being deploy in a docker container so I can't access the jboss home directory. 

I'm wondering if its possible to pass in the data or files needed to start wildfly instead of using the jboss home path.

**Comment by tobias** [comment]
Is this for Immutant 1 or 2? What task are you trying to use? For 2, you only need to give the plugin a home dir if you want to generate the war file directly in the `standalone/deployments/` dir (which is just a convenience), or for running tests within the container.

**Comment by chipset1** [comment]
Immutant 2. I'm using it to test wars in the wildfly.

I'm wondering if the home dir is needed with wildfly installed locally? or if theres a way to deploy and test the war remotely?

**Comment by tobias** [comment]
The test task currently uses `JBOSS_HOME` to make an isolated copy of WildFly, giving it full control over the ports the server listens on, and preventing it from interfering with a server running on the default ports if you are using one for development. However, it does use the management api to deploy the application remotely. 

The plugin is really just sugar around https://github.com/immutant/fntest, so you should be able to use fntest directly if you want to test against a server that is already running. If you need help with that, we'd be happy to give it. The quickest way would be to come see us in `#immutant` on Freenode IRC or the Clojurians Slack.

**Comment by chipset1** [comment]
Cool, I'll look into fntest and see if i can get it working. I'll pop into the IRC channel if i need help. Thanks!
