### ISSUE TITLE
Handle deploying an existing .ima

### ISSUE THREAD

**Issue by arnaudbos** [immutant/lein-immutant#84]
Question:

    arnaudbos> Hello! I'm wondering, is it possible to deploy a .ima archive to immutant without have the source code locally?
    arnaudbos> Reading the doc I see: "The deploy subtask optionally accepts the path to the project."
    arnaudbos> "project", not "archive"
    arnaudbos> and also: "A new .ima archive will be generated each time deploy is invoked."
    arnaudbos> is it possible with the lein-immutant plugin I mean, I can do it manually otherwise

Answer:

    tcrawley> the plugin doesn't currently handle deploying an existing .ima for you. You have to do it manually
    tcrawley> though it wouldn't be difficult to add that. can you file an issue at https://github.com/immutant/lein-immutant/issues?state=open ?

Let me know if I can help!

**Comment by tobias** [comment]
Closed, since 1.x is no longer under active development, and 2.x doesn't handle deployment.
